### ISSUE TITLE
How do I suppress z/x/y-coordinates in the Adressbar /  make static adressbar

### ISSUE THREAD

**Issue by ffischer1984** [sebastianoscarlopez/foss4g2022-react-maplibre#1]
Hi guys,

thanks a lot for this great example at the foss4g2022 in Firenze.

This example shows the current zoomlevels and the x/y-tile coordinates in the adressbar of the browser e.g http://localhost:3000/#9.38/-34.463/-57.9948/0/45

Is there any chance to have a static address like http://localhost:3000/

Not sure if it's a maplibre or reactjs question but I have absolutely no clue why the address is changing and how I could make it static...maybe you have?? Would be even happy for a hint

Thanks a lot guys

**Comment by sebastianoscarlopez** [comment]
Hi @ffischer1984, the `hash` property is what you are looking for.

Change `hash: true` to `hash: false` in this file https://github.com/sebastianoscarlopez/foss4g2022-react-maplibre/blob/main/src/components/map/Map.js
